In [12]:
import tensorflow as tf
a=3#创建变量
w=tf.Variable([[0.5,1.0]])#把这个行向量转化为tensorflow的格式
x=tf.Variable([[2.0],[1.0]])#列向量
y=tf.matmul(w,x)#进行矩阵的乘法
print (w)
#简单的w*x这么麻烦，对tf也是醉了 
int_top=tf.global_variables_initializer()#
with tf.Session() as sess:#初始化再session里面进行的
    sess.run(int_top)
    print (y.eval())

<tf.Variable 'Variable_18:0' shape=(1, 2) dtype=float32_ref>
[[ 2.]]


In [14]:
#可以和numpy对比一下看看 最好都用float32的
norm=tf.random_normal([2,3],mean=-1,stddev=4)
#shuffle the first dimension
c=tf.constant([[1,2],[3,4],[5,6]])
shuff=tf.random_shuffle(c)
#再tensorflow中进行一个操作一定要先创建session，然后才能执行操作
sess=tf.Session()
print (sess.run(norm))
print (sess.run(shuff))

[[ 0.51443636 -2.00240898 -1.08036768]
 [-0.37550694 -0.03160679  1.06559968]]
[[3 4]
 [1 2]
 [5 6]]


In [15]:
#实现一个自增1的程序，虽然复杂，但是再tensorflow里面，进行复杂的操作和简单的操作，代码量其实事差不多的
state=tf.Variable(0)#创建一个0，并转化为tf的格式
new_value=tf.add(state,tf.constant(1))#每次增加1
update=tf.assign(state,new_value)#替换操作

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print (sess.run(state))#执行把0给state的操作
    for _ in range(3):
        sess.run(update)
        print (sess.run(state))
    

0
1
2
3


In [ ]:
tf.zeros([3, 4], int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

# 'tensor' is [[1, 2, 3], [4, 5, 6]]
tf.zeros_like(tensor) ==> [[0, 0, 0], [0, 0, 0]]
tf.ones([2, 3], int32) ==> [[1, 1, 1], [1, 1, 1]]

# 'tensor' is [[1, 2, 3], [4, 5, 6]]
tf.ones_like(tensor) ==> [[1, 1, 1], [1, 1, 1]]

# Constant 1-D Tensor populated with value list.
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7]) => [1 2 3 4 5 6 7]

# Constant 2-D tensor populated with scalar value -1.
tensor = tf.constant(-1.0, shape=[2, 3]) => [[-1. -1. -1.]
                                              [-1. -1. -1.]]

tf.linspace(10.0, 12.0, 3, name="linspace") => [ 10.0  11.0  12.0]

# 'start' is 3
# 'limit' is 18
# 'delta' is 3
tf.range(start, limit, delta) ==> [3, 6, 9, 12, 15]

In [16]:
import numpy as np
a=np.zeros((3,3))
#虽然numpy可以转化为tensorflow的格式，但是我们一般是通过session的格式来转换的
ta=tf.convert_to_tensor(a)
with tf.Session() as sess:
    print (sess.run(ta))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [20]:
#基本操作http://blog.csdn.net/xxzhangx/article/details/54606040
input1=tf.placeholder(tf.float32)#先占两个位置，类似于先定义一个变量，里面事float32位的
input2=tf.placeholder(tf.float32)
output=tf.mul(input1,input2)#执行相乘的操作
with tf.Session() as sess:
    print (sess.run([output],feed_dict={input1:[7.],input2:[2.]}))#后面参数通过run的时候赋值

AttributeError: module 'tensorflow' has no attribute 'mul'

In [27]:
import tensorflow as tf
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
y = tf._mul(a, b)
sess = tf.Session() 
print (sess.run(y, feed_dict={a: 3, b: 3}))

AttributeError: module 'tensorflow' has no attribute '_mul'

In [28]:
import tensorflow as tf
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
y = tf.sub(a, b)
sess = tf.Session() 
print (sess.run(y, feed_dict={a: 3, b: 3}))

AttributeError: module 'tensorflow' has no attribute 'sub'

In [ ]:
import tensorflow as tf
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
y = tf.div(a, b)
sess = tf.Session() 
print (sess.run(y, feed_dict={a: 3, b: 3}))

In [ ]:
#取模
import tensorflow as tf
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
y = tf.mod(a, b)
sess = tf.Session() 
print (sess.run(y, feed_dict={a: 3, b: 3}))