In [1]:
import numpy as np

# 数组与标量、数组之间的运算

In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
# 与标量的运算
print(arr+10)
print(arr-10)
print(arr*10)
print(arr/10)
print(arr**2)

[11 12 13 14 15]
[-9 -8 -7 -6 -5]
[10 20 30 40 50]
[ 0.1  0.2  0.3  0.4  0.5]
[ 1  4  9 16 25]


In [15]:
# 数组与数组之间的运算   应用于元素级的操作
arr1 = np.random.randint(1,9,5)
arr2 = np.random.randint(1,9,5)
print(arr1)
print(arr2)

[5 6 4 7 4]
[2 1 6 2 8]


In [16]:
arr1+arr2

array([ 7,  7, 10,  9, 12])

In [17]:
arr1 = np.random.randint(1,9,(3,3))
arr2 = np.random.randint(1,9,(3,3))
print(arr1)
print(arr2)

[[2 3 5]
 [8 6 1]
 [3 3 6]]
[[3 7 3]
 [8 3 1]
 [1 8 3]]


In [18]:
arr1+arr2

array([[ 5, 10,  8],
       [16,  9,  2],
       [ 4, 11,  9]])

In [19]:
arr1*arr2

array([[ 6, 21, 15],
       [64, 18,  1],
       [ 3, 24, 18]])

In [20]:
arr1/arr2

array([[ 0.66666667,  0.42857143,  1.66666667],
       [ 1.        ,  2.        ,  1.        ],
       [ 3.        ,  0.375     ,  2.        ]])

In [21]:
arr1**arr2

array([[       8,     2187,      125],
       [16777216,      216,        1],
       [       3,     6561,      216]], dtype=int32)

In [23]:
'''
    广播
'''
arr1 = np.random.randint(1,9,(3,4))
arr2 =  np.random.randint(1,9,3)
print(arr1)
print(arr2)

[[3 2 3 2]
 [5 4 7 3]
 [3 2 2 5]]
[4 4 5]


In [26]:
arr1 = arr1.reshape(4,3)
arr1

array([[3, 2, 3],
       [2, 5, 4],
       [7, 3, 3],
       [2, 2, 5]])

In [27]:
arr1+arr2

array([[ 7,  6,  8],
       [ 6,  9,  9],
       [11,  7,  8],
       [ 6,  6, 10]])

In [28]:
# 两个形状不同的数组只要满足对应维度上的数量相同或者为1  则两个数组可以进行运算  
# 维度小的数组会默认增加一个维度
print(arr1.shape)      
print(arr2.shape)

(4, 3)
(3,)


In [32]:
arr5 = np.random.randint(1,9,(3,2,4))   
arr6 = np.random.randint(1,9,(2,3))  

print(arr5)
print(arr6)

[[[2 2 6 8]
  [4 4 7 5]]

 [[7 4 4 1]
  [2 1 2 4]]

 [[7 8 5 4]
  [4 8 7 3]]]
[[2 3 8]
 [1 7 7]]


In [33]:
arr6.shape

(2, 3)

In [34]:
arr6 = arr6.reshape(3,2,-1)
arr6

array([[[2],
        [3]],

       [[8],
        [1]],

       [[7],
        [7]]])

In [35]:
arr6.shape

(3, 2, 1)

In [36]:
arr5+arr6

array([[[ 4,  4,  8, 10],
        [ 7,  7, 10,  8]],

       [[15, 12, 12,  9],
        [ 3,  2,  3,  5]],

       [[14, 15, 12, 11],
        [11, 15, 14, 10]]])

# 数组的矩阵积

In [38]:
arr1 = np.random.randint(1,5,(3,3))
arr2 = np.random.randint(1,5,(3,2))
print(arr1)
print(arr2)

[[1 2 1]
 [4 4 3]
 [4 2 1]]
[[2 1]
 [4 4]
 [1 4]]


In [39]:
arr1.dot(arr2)

array([[11, 13],
       [27, 32],
       [17, 16]])

# 多维数组的索引

In [40]:
arr1 = np.random.randint(1,9,(4,3,4))
arr1

array([[[8, 6, 8, 6],
        [8, 4, 4, 7],
        [3, 4, 7, 4]],

       [[6, 3, 8, 3],
        [3, 5, 2, 2],
        [2, 4, 8, 3]],

       [[5, 2, 4, 7],
        [1, 1, 5, 7],
        [5, 3, 3, 5]],

       [[4, 2, 1, 8],
        [6, 3, 1, 6],
        [7, 8, 6, 3]]])

In [44]:
arr1[0,1,1]

4

In [45]:
arr1 = np.random.randint(1,9,(4,3,4))
arr1

array([[[2, 1, 7, 6],
        [3, 4, 5, 7],
        [7, 8, 4, 4]],

       [[3, 3, 8, 6],
        [2, 6, 7, 3],
        [4, 3, 8, 5]],

       [[7, 6, 7, 1],
        [8, 5, 5, 1],
        [2, 3, 2, 5]],

       [[7, 7, 3, 1],
        [3, 6, 8, 5],
        [2, 2, 6, 4]]])

In [48]:
'''
    切片
'''
arr1[0,1,1:3]

array([4, 5])

In [51]:
arr1[1:3,1,1:3]

array([[6, 7],
       [5, 5]])

In [52]:
arr1[:,1:,1:3]

array([[[4, 5],
        [8, 4]],

       [[6, 7],
        [3, 8]],

       [[5, 5],
        [3, 2]],

       [[6, 8],
        [2, 6]]])

In [56]:
'''
    切片操作获取的是视图，新数组修改会影响原数组
'''
x = arr1[0,1,1:3]
x[:] = 0
x

array([0, 0])

In [57]:
arr1

array([[[2, 1, 7, 6],
        [3, 0, 0, 7],
        [7, 8, 4, 4]],

       [[3, 3, 8, 6],
        [2, 6, 7, 3],
        [4, 3, 8, 5]],

       [[7, 6, 7, 1],
        [8, 5, 5, 1],
        [2, 3, 2, 5]],

       [[7, 7, 3, 1],
        [3, 6, 8, 5],
        [2, 2, 6, 4]]])

In [58]:
'''
    花式索引
'''
arr = np.arange(30).reshape(6,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [62]:
# 获取0 3 5 行数据
arr[[0,3,5]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [65]:
arr[[0,3,5],0::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [25, 27, 29]])

In [66]:
arr[[0,3,5],[0,1,3]]

array([ 0, 16, 28])

In [67]:
arr[np.ix_([0,3,5],[0,1,3])]   # 通过索引器 np.ix_() 可以分别获取每一行的  0 1 3下标的元素

array([[ 0,  1,  3],
       [15, 16, 18],
       [25, 26, 28]])

In [69]:
'''
    通过花式索引获取的新数组是一个副本，新数组修改不会影响原数组
'''
x = arr[np.ix_([0,3,5],[0,1,3])] 
x[:] = 100
x

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [70]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [71]:
'''
    布尔索引
'''
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [72]:
condition = [True,False,True,False,True]
condition

[True, False, True, False, True]

In [76]:
arr1[condition]

array([1, 3, 5])

In [87]:
'''
    练习强化
'''
names = np.array(['joe','anne','tom'])
scores = np.array([
    [80,85,89],
    [79,89,90],
    [88,76,89]
])

classes =  np.array(['语文','数学','英语'])
print(names)
print(scores)
print(classes)

['joe' 'anne' 'tom']
[[80 85 89]
 [79 89 90]
 [88 76 89]]
['语文' '数学' '英语']


In [79]:
# 输出joe的成绩
names == 'joe'

array([ True, False, False], dtype=bool)

In [80]:
scores[[ True, False, False]]

array([[80, 85, 89]])

In [81]:
scores[names=='joe']

array([[80, 85, 89]])

In [92]:
# 输出joe的数学成绩
scores[names=='joe',classes=='数学']

array([85])

In [88]:
classes=='数学'

array([False,  True, False], dtype=bool)

In [94]:
# 输出joe 和 anne的成绩
scores[(names=='joe')| (names=='anne')]   # or

array([[80, 85, 89],
       [79, 89, 90]])

In [95]:
# 输出不是joe 和 anne 的成绩
scores[(names!='joe')& (names!='anne')]   # and

array([[88, 76, 89]])

# 数组的转置与轴对换

In [113]:
arr = np.random.randint(1,9,(3,4))
print(arr.shape)
arr

(3, 4)


array([[6, 5, 5, 5],
       [4, 6, 6, 3],
       [5, 1, 2, 1]])

In [114]:
print(arr[1,0])

4


In [115]:
# 通过大写的 T 进行转置
arr = arr.T
arr

array([[6, 4, 5],
       [5, 6, 1],
       [5, 6, 2],
       [5, 3, 1]])

In [116]:
print(arr.shape)

(4, 3)


In [117]:
print(arr[0,1])

4


In [134]:
'''
    使用 transppose 进行轴转置
'''
arr = np.random.randint(1,9,(3,4,2))
print(arr.shape)
arr

(3, 4, 2)


array([[[5, 2],
        [6, 7],
        [1, 7],
        [1, 1]],

       [[8, 2],
        [1, 2],
        [1, 1],
        [3, 2]],

       [[3, 4],
        [6, 1],
        [2, 3],
        [4, 6]]])

In [131]:
arr = arr.transpose(1,2,0)   #
arr

array([[[7, 6, 2],
        [6, 3, 7]],

       [[4, 6, 3],
        [8, 2, 4]],

       [[1, 1, 2],
        [5, 4, 3]],

       [[7, 1, 8],
        [7, 5, 6]]])

In [122]:
print(arr.shape)

(2, 4, 3)


In [ ]:
3  4   2    数量
0  1   2    维度的下标

4  3   2
1  0   2    维度的下标

2  3   4
2  0   1    维度的下标

In [135]:
arr = arr.transpose(2,0,1)   #
arr

array([[[5, 6, 1, 1],
        [8, 1, 1, 3],
        [3, 6, 2, 4]],

       [[2, 7, 7, 1],
        [2, 2, 1, 2],
        [4, 1, 3, 6]]])

# 数组的拉伸与合并

In [220]:
arr = np.random.randint(1,9,(2,2))
arr

array([[5, 5],
       [6, 5]])

In [221]:
# tile 进行拉伸
np.tile(arr,2)

array([[5, 5, 5, 5],
       [6, 5, 6, 5]])

In [222]:
np.tile(arr,(3,2))

array([[5, 5, 5, 5],
       [6, 5, 6, 5],
       [5, 5, 5, 5],
       [6, 5, 6, 5],
       [5, 5, 5, 5],
       [6, 5, 6, 5]])

In [224]:
np.tile(arr,(3,1))

array([[5, 5],
       [6, 5],
       [5, 5],
       [6, 5],
       [5, 5],
       [6, 5]])

In [231]:
'''
    数组的合并
'''
a = [1,2,3,4]
b = [10,20,30,40]

In [232]:
# stack 合并数组
np.stack((a,),axis = 0)             

array([[1, 2, 3, 4]])

In [233]:
np.stack((a,),axis = 1)    

array([[1],
       [2],
       [3],
       [4]])

In [234]:
np.stack((a,b),axis = 0) 

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [235]:
np.stack((a,b),axis = 1) 

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [ ]:
[[1,10],[2,20],[3,30],[4,40]]

In [236]:
c = [[1,2,3,4],[5,6,7,8]]
d = [[10,20,30,40],[50,60,70,80]]

In [237]:
np.stack((c,),axis = 0)

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [238]:
np.stack((c,),axis = 1)

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [239]:
np.stack((c,),axis = 2)

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [240]:
np.stack((c,d),axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [241]:
np.stack((c,d),axis = 1)

array([[[ 1,  2,  3,  4],
        [10, 20, 30, 40]],

       [[ 5,  6,  7,  8],
        [50, 60, 70, 80]]])

In [242]:
np.stack((c,d),axis = 2)

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30],
        [ 4, 40]],

       [[ 5, 50],
        [ 6, 60],
        [ 7, 70],
        [ 8, 80]]])

In [244]:
# vstck   纵向合并
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [245]:
np.vstack((c,d))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [246]:
# hstack
np.hstack((a,b))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [247]:
np.hstack((c,d))

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

# 通用一元函数

In [136]:
'''
    abs fabs  绝对值函数
'''
arr = np.array([-1,1,-2,2])
arr

array([-1,  1, -2,  2])

In [138]:
np.fabs(arr)

array([ 1.,  1.,  2.,  2.])

In [139]:
'''
    sqrt  开根号
'''
arr = np.random.randint(1,9,(3,3))
arr

array([[4, 6, 7],
       [3, 6, 3],
       [1, 6, 7]])

In [140]:
np.sqrt(arr)

array([[ 2.        ,  2.44948974,  2.64575131],
       [ 1.73205081,  2.44948974,  1.73205081],
       [ 1.        ,  2.44948974,  2.64575131]])

In [141]:
'''
    square  开平方
'''
np.square(arr)

array([[16, 36, 49],
       [ 9, 36,  9],
       [ 1, 36, 49]], dtype=int32)

In [146]:
'''
    exp  指数e的X次方
    e:2.71828
'''
np.exp(arr)

array([[   54.59815003,   403.42879349,  1096.63315843],
       [   20.08553692,   403.42879349,    20.08553692],
       [    2.71828183,   403.42879349,  1096.63315843]])

In [155]:
'''
    log 对数函数
'''
arr = np.random.randint(1,9,5)
arr

array([6, 7, 7, 4, 2])

In [156]:
np.log(arr)

array([ 1.79175947,  1.94591015,  1.94591015,  1.38629436,  0.69314718])

In [157]:
np.log10(arr)

array([ 0.77815125,  0.84509804,  0.84509804,  0.60205999,  0.30103   ])

In [158]:
np.log2(arr)

array([ 2.5849625 ,  2.80735492,  2.80735492,  2.        ,  1.        ])

In [159]:
np.log1p(arr)

array([ 1.94591015,  2.07944154,  2.07944154,  1.60943791,  1.09861229])

In [160]:
# 换底公式
np.log(3)/np.log(arr)

array([ 0.61314719,  0.56457503,  0.56457503,  0.79248125,  1.5849625 ])

In [166]:
'''
    向上取整 和 向下取整
'''
arr = np.array([1.236,4.438,5.567])
arr

array([ 1.236,  4.438,  5.567])

In [167]:
np.ceil(arr)  # 向上

array([ 2.,  5.,  6.])

In [168]:
np.floor(arr)

array([ 1.,  4.,  5.])

In [170]:
'''
   四舍五入 
'''
np.rint(arr)
np.round(arr,2)

array([ 1.24,  4.44,  5.57])

In [171]:
'''
    isnan
'''
arr = np.array([1,2,3,np.NaN,4])
arr

array([  1.,   2.,   3.,  nan,   4.])

In [172]:
np.isnan(arr)

array([False, False, False,  True, False], dtype=bool)

In [174]:
arr[~np.isnan(arr)]   # 过去掉NaN的数据

array([ 1.,  2.,  3.,  4.])

In [183]:
arr = np.array([1,2,3,np.NaN,4,np.inf,np.pi,np.e])
arr

array([ 1.        ,  2.        ,  3.        ,         nan,  4.        ,
               inf,  3.14159265,  2.71828183])

In [184]:
np.isfinite(arr)   # 哪些是有穷的

array([ True,  True,  True, False,  True, False,  True,  True], dtype=bool)

In [185]:
np.isinf(arr)     #哪些是无穷的 

array([False, False, False, False, False,  True, False, False], dtype=bool)

In [186]:
'''
    三角函数
'''
arr = np.array([1,2,3,4,5,6])
arr
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

# 二元函数


In [187]:
'''
    mod
'''
arr1 = np.random.randint(1,9,5)
arr2 = np.random.randint(1,9,5)
print(arr1)
print(arr2)

[8 8 3 3 7]
[3 1 8 2 6]


In [188]:
np.mod(arr1,arr2)

array([2, 0, 3, 1, 1], dtype=int32)

In [189]:
np.greater(arr1,arr2)  # 大于

array([ True,  True, False,  True,  True], dtype=bool)

In [190]:
np.less(arr1,arr2)  # 小于

array([False, False,  True, False, False], dtype=bool)

In [191]:
np.equal(arr1,arr2)  # 等于

array([False, False, False, False, False], dtype=bool)

In [193]:
arr1 = np.array([0,1,1,0])
arr2 = np.array([1,0,1,0])

In [194]:
np.logical_and(arr1,arr2)

array([False, False,  True, False], dtype=bool)

In [195]:
np.logical_or(arr1,arr2)

array([ True,  True,  True, False], dtype=bool)

In [196]:
np.logical_xor(arr1,arr2)

array([ True,  True, False, False], dtype=bool)

In [197]:
np.power(arr1,2)  # 指数函数

array([0, 1, 1, 0], dtype=int32)

In [198]:
'''
    聚合函数
'''
arr = np.random.randint(1,9,(3,3))
arr

array([[5, 1, 2],
       [2, 1, 4],
       [2, 5, 4]])

In [201]:
print('最小值:',arr.min())
print('最大值:',arr.max())
print('平均值:',arr.mean())
print('标准差:',arr.std())

最小值: 1
最大值: 5
平均值: 2.88888888889
标准差: 1.52347880009


In [203]:
print('最小值:',arr.min(axis = 0))
[0,0] [1,0] [2,0]  2
[0,1] [1,1] [2,1]  1
[0,2] [1,2] [2,2]  2
print('最小值:',arr.min(axis = 1))
[0,0] [0,1] [0,2]  1
[1,0] [1,1] [1,2]  1
[2,0] [2,1] [2,2]  2

最小值: [2 1 2]
最小值: [1 1 2]


In [204]:
arr = np.random.randint(1,9,(3,3,2))
arr

array([[[6, 8],
        [4, 8],
        [1, 2]],

       [[3, 4],
        [8, 8],
        [1, 3]],

       [[1, 6],
        [4, 6],
        [3, 4]]])

In [205]:
arr.min(axis = 0)
[0,0,0] [1,0,0] [2,0,0]  1
[0,0,1] [1,0,1] [2,0,1]  4



array([[1, 4],
       [4, 6],
       [1, 2]])

In [206]:
# 方差
arr = np.random.randint(1,9,(3,3))
arr

array([[4, 3, 3],
       [4, 7, 8],
       [7, 5, 6]])

In [208]:
np.mean((arr-arr.mean())**2)

3.0617283950617287

In [209]:
np.sqrt(np.mean((arr-arr.mean())**2))

1.7497795275581802

In [210]:
np.std(arr)

1.7497795275581802

In [211]:
'''
    where 函数
'''
arr1 = np.array([1,3,5,2,4])
arr2 = np.array([2,2,6,3,3])
print(arr1)
print(arr2)


[1 3 5 2 4]
[2 2 6 3 3]


In [212]:
condition = arr1<arr2
condition

array([ True, False,  True,  True, False], dtype=bool)

In [213]:
new_array = [x if c else y  for x,y,c in zip(arr1,arr2,condition)]
new_array

[1, 2, 5, 2, 3]

In [214]:
np.where([ True, False,  True,  True, False],[1 3 5 2 4],[2 2 6 3 3])

array([1, 2, 5, 2, 3])

In [219]:
?np.where

In [216]:
np.where([[True, False], [True, True]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])


array([[1, 8],
       [3, 4]])

In [217]:
'''
    unique  去重函数
'''
arr = np.random.randint(1,5,9)
arr

array([3, 4, 1, 4, 2, 4, 2, 4, 3])

In [218]:
np.unique(arr)

array([1, 2, 3, 4])