# NumPy核心数据结构：ndarray

In [1]:
import numpy as np

# ndarray创建

In [2]:
# array函数
?np.array# 参数列表：序列、数据类型、是否copy数据、是否排序，等等

In [57]:
# 使用列表创建
list1=[1,2,3,4,5]
print('使用list创建：')
np.array(list1)

使用list创建：


array([1, 2, 3, 4, 5])

In [58]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print('a=',a)
print('b=',b)

a= [1 2 3]
b= [4 5 6]


In [59]:
# 二维列表创建
list2=[
    [1,2,3,4],
    [5,6,7,8]
]
print('二维列表：\n')
np.array(list2)

二维列表：



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print('==a==')
print(a)

==a==
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
b=np.array([
    [
        [1,2,3,4],
        [4,5,6,7],
        [5,6,7,8]
    ],
    [
        [10,20,30,40],
        [20,30,40,50],
        [50,60,70,80]
    ]
           ])
print(b)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [20 30 40 50]
  [50 60 70 80]]]


In [62]:
# 使用元组
tuple1=(1,2,3,4,5)
print('使用元组创建：')
np.array(tuple1)

使用元组创建：


array([1, 2, 3, 4, 5])

In [63]:
tuple2=(
    (1,2,3,4),
    (5,6,7,8)
)
print('二维元组创建：\n')
np.array(tuple2)

二维元组创建：



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
b=np.array((
    (
        (1,2,3,4),(4,5,6,7),(7,8,9,9)
    ),
    (
        (4,5,6,7),(2,3,5,6),(7,8,9,1)
    )
))
print(b)

[[[1 2 3 4]
  [4 5 6 7]
  [7 8 9 9]]

 [[4 5 6 7]
  [2 3 5 6]
  [7 8 9 1]]]


In [65]:
# zeros 创建全零数组
print('生成全零数组：',np.zeros(3))
print('生成多维全零数组：')
np.zeros((3,3))

生成全零数组： [0. 0. 0.]
生成多维全零数组：


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
# ones 创建全1数组
print('生成全1数组：',np.ones(5))
print('生成多维全1数组：')
np.ones((3,2))

生成全1数组： [1. 1. 1. 1. 1.]
生成多维全1数组：


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
#  empty 创建未初始化数组
print('生成empty数组：',np.empty(4))
print('生成多维empty数组：')
np.empty((2,3))

生成empty数组： [0.66666667 0.33333333 1.         5.        ]
生成多维empty数组：


array([[1., 1., 1.],
       [1., 1., 1.]])

# ndarray其他创建方式

In [68]:
np.arange(20)# 默认获取[0,20)区间，步长为1的数据

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
np.arange(10,20)# 指定开始数据为10，获取数据区间为[10,20)，步长为1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [70]:
np.arange(10,20,2)#指定步长为2

array([10, 12, 14, 16, 18])

In [71]:
np.arange(20,15,-1)#指定步长为-1

array([20, 19, 18, 17, 16])

In [72]:
np.linspace(0,10,5)#形成一个包含5个元素的数组，元素之间是等差数列变化，差值为2.5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [73]:
?np.linspace

In [74]:
np.logspace(0,2,5)#0表示10的0次方，2表示10的2次方，5表示最终生成的元素数量为5个（可以通过参数base来指定具体的底数）

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [75]:
?np.logspace

In [76]:
np.random.random((3,2,3))#指定数组的大小形状

array([[[0.52531624, 0.5070507 , 0.97791487],
        [0.78215113, 0.86131964, 0.7954182 ]],

       [[0.31519769, 0.87810993, 0.17264876],
        [0.13336412, 0.62131788, 0.29713875]],

       [[0.29121418, 0.02317707, 0.37325202],
        [0.3236501 , 0.61746325, 0.5587603 ]]])

In [77]:
# 返回一个样本具有标准正态分布
arr=np.random.randn(3,3)
print(arr)

[[ 0.48470668 -1.06109799 -0.32890007]
 [-1.27795145  0.54993119 -0.13067846]
 [ 0.45968238  1.48434219 -0.92306683]]


In [78]:
# 返回随机的整数
arr=np.random.randint(1,9,size=(3,3))
print(arr)

[[2 2 1]
 [1 1 1]
 [1 4 7]]


In [79]:
# 返回0到1的随机值
arr=np.random.rand(9) # rand根据维度生成[0,1)之间的数据，包含0，不包含1
print(arr)

[0.82699971 0.20330367 0.8066971  0.94788713 0.01200761 0.17529617
 0.42023533 0.26563507 0.87185435]


# ndarray对象属性

In [80]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print('维度的数量：',a.ndim)
print('数组的形状：',a.shape)
print('数组的元素类型：',a.dtype)
print('数组的元素数量：',a.size)

维度的数量： 2
数组的形状： (3, 3)
数组的元素类型： int32
数组的元素数量： 9


# ndarray中元素数据类型

In [81]:
a2=np.array([1,2,3,4])
print(a2.dtype)
a3=a2.astype(float)# 类型转换要求支持类型的转换
print(a2.dtype)
print(a3.dtype)

int32
int32
float64


# NumPy基本数据类型

In [82]:
d=np.array(['Python','Scala','Java','C#'])
d

array(['Python', 'Scala', 'Java', 'C#'], dtype='<U6')

In [83]:
d.dtype

dtype('<U6')

In [84]:
e=np.array(['Python','Scala','Java','C#'],dtype='S8')
e

array([b'Python', b'Scala', b'Java', b'C#'], dtype='|S8')

In [85]:
arr=np.array([129,2,3,4],dtype=np.int32)
print(arr.dtype)
arr

int32


array([129,   2,   3,   4])

In [86]:
#大端小端：
# 一种是将低序字节存储在起始地址，这称为小端(little-endian)字节序；
# 另一种方法是将高序字节存储在起始地址，这称为大端(big-endian)字节序。

In [87]:
arr=np.array([129,2,3,4],dtype='S2')
arr

array([b'12', b'2', b'3', b'4'], dtype='|S2')

In [88]:
arr=np.array([129,2,3,4],dtype='float32')
arr

array([129.,   2.,   3.,   4.], dtype=float32)

In [89]:
arr=np.array([129,2,3,4],dtype='i8')
arr

array([129,   2,   3,   4], dtype=int64)

# ndarray修改形状

In [90]:
a=np.arange(0,20,2)
print(a)
print(a.size)

[ 0  2  4  6  8 10 12 14 16 18]
10


In [91]:
a.reshape(-1,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [92]:
a.reshape(5,-1)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [93]:
# reshape修改复制之后的数组形状，shape修改原数组的形状
print(a.shape)
a.shape=(2,-1)
a

(10,)


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [94]:
b=a.reshape(2,5)
print(b)
print(b.size)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]
10


In [95]:
b[0][1]=100
print(a)
print(b)

[[  0 100   4   6   8]
 [ 10  12  14  16  18]]
[[  0 100   4   6   8]
 [ 10  12  14  16  18]]


# 数组与标量、数组之间的运算

In [96]:
arr1=np.array([1,1,2,3])
arr2=np.array([2,1,6,3])
arr1+arr2

array([3, 2, 8, 6])

In [97]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1+4)
print(arr1*5)
print(arr1-3)
print(arr1/2.0)
print(1.0/arr1)
print(arr1**2)
print(2**arr1)

[1 2 3 4 5]
[5 6 7 8 9]
[ 5 10 15 20 25]
[-2 -1  0  1  2]
[0.5 1.  1.5 2.  2.5]
[1.         0.5        0.33333333 0.25       0.2       ]
[ 1  4  9 16 25]
[ 2  4  8 16 32]


In [98]:
arr1=np.array([
    [1,2,3],
    [4,5,6]
])
arr2=np.array([
    [4.6,3.2,2.1],
    [5.2,4.3,3.4]
])
print('=====arr1+arr2=====')
print(arr1+arr2)
print('=====arr1-arr2=====')
print(arr1-arr2)
print('=====arr1*arr2=====')
print(arr1*arr2)
print('=====arr1/arr2=====')
print(arr1/arr2)
print('=====arr1**arr2=====')
print(arr1**arr2)

=====arr1+arr2=====
[[5.6 5.2 5.1]
 [9.2 9.3 9.4]]
=====arr1-arr2=====
[[-3.6 -1.2  0.9]
 [-1.2  0.7  2.6]]
=====arr1*arr2=====
[[ 4.6  6.4  6.3]
 [20.8 21.5 20.4]]
=====arr1/arr2=====
[[0.2173913  0.625      1.42857143]
 [0.76923077 1.1627907  1.76470588]]
=====arr1**arr2=====
[[1.00000000e+00 9.18958684e+00 1.00451086e+01]
 [1.35117610e+03 1.01291037e+03 4.42297262e+02]]


In [2]:
# 数组的广播
arr1=np.random.randint(1,9,(2,3))
print(arr1)
arr2=np.array([2,3,4])
print(arr2)

[[8 2 8]
 [4 1 8]]
[2 3 4]


In [3]:
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3,)


In [4]:
arr1+arr2

array([[10,  5, 12],
       [ 6,  4, 12]])

In [5]:
# 广播 : 如果两个数组的轴长度相符，或其中的一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。(在维度更低的数组的第一位加上一个1 )
arr1=np.random.randint(1,9,(3,2))
arr2=np.random.randint(1,9,(2))
print(arr1)
print(arr2)
print(arr1+arr2)

[[8 4]
 [7 4]
 [6 2]]
[2 7]
[[10 11]
 [ 9 11]
 [ 8  9]]


In [12]:
arr1=np.random.randint(1,9,(3,2,2))
# arr2=np.random.randint(1,9,(3,2))   # 无法直接广播
# arr2=np.random.randint(1,9,(2,3))
# arr2=np.random.randint(1,9,(3)) 
arr2=np.random.randint(1,9,(2,1)) 
print(arr1)
print(arr2)
print(arr1+arr2)

[[[7 7]
  [8 7]]

 [[8 5]
  [4 5]]

 [[7 5]
  [6 3]]]
[[3]
 [3]]
[[[10 10]
  [11 10]]

 [[11  8]
  [ 7  8]]

 [[10  8]
  [ 9  6]]]


# 数组的矩阵积

In [102]:
arr=np.array([
    [120,60,220],
    [115,23,201],
    [132,48,230]
])
arr2=np.array([
    [12.34,0.04],
    [204.56,2.34],
    [9.89,0.45]
])
arr.dot(arr2)

array([[15930.2 ,   244.2 ],
       [ 8111.87,   148.87],
       [13722.46,   221.1 ]])

In [103]:
np.dot(arr,arr2)

array([[15930.2 ,   244.2 ],
       [ 8111.87,   148.87],
       [13722.46,   221.1 ]])

# 多维数组的索引

In [104]:
arr=np.array([
    [
        [2,3,4,5],[1,3,4,9]
    ],
    [
        [0,3,4,8],[2,4,9,4]
    ],
    [
        [1,4,5,8],[2,5,6,8]
    ],
    [
        [2,3,6,8],[3,4,8,9]
    ]
])
arr.shape

(4, 2, 4)

In [105]:
arr[3]

array([[2, 3, 6, 8],
       [3, 4, 8, 9]])

In [106]:
arr[3][1]

array([3, 4, 8, 9])

In [107]:
arr[3][1][2]

8

In [108]:
arr[3,1,2]

8

# 数组的切片

In [109]:
arr

array([[[2, 3, 4, 5],
        [1, 3, 4, 9]],

       [[0, 3, 4, 8],
        [2, 4, 9, 4]],

       [[1, 4, 5, 8],
        [2, 5, 6, 8]],

       [[2, 3, 6, 8],
        [3, 4, 8, 9]]])

In [110]:
arr[1]

array([[0, 3, 4, 8],
       [2, 4, 9, 4]])

In [111]:
arr[1][0]

array([0, 3, 4, 8])

In [112]:
arr[1][0][1:3]

array([3, 4])

In [113]:
arr[1][1][1:3]

array([4, 9])

In [114]:
arr[1,:,1:3]

array([[3, 4],
       [4, 9]])

In [115]:
# 切片操作获取的是视图，会影响原数组的值
arr2=arr[:,1:3,1:3]
print(arr2)
arr2[:]=100
print(arr2)

[[[3 4]]

 [[4 9]]

 [[5 6]]

 [[4 8]]]
[[[100 100]]

 [[100 100]]

 [[100 100]]

 [[100 100]]]


In [116]:
# 查看原数组
arr

array([[[  2,   3,   4,   5],
        [  1, 100, 100,   9]],

       [[  0,   3,   4,   8],
        [  2, 100, 100,   4]],

       [[  1,   4,   5,   8],
        [  2, 100, 100,   8]],

       [[  2,   3,   6,   8],
        [  3, 100, 100,   9]]])

In [117]:
# 创建一个二维数组
new_arr=np.random.randint(1,9,(4,8))
new_arr

array([[7, 7, 2, 2, 8, 2, 7, 6],
       [4, 3, 2, 5, 5, 8, 1, 3],
       [8, 2, 7, 3, 5, 5, 6, 3],
       [7, 4, 4, 3, 8, 4, 3, 1]])

In [118]:
# 修改值
new_arr[:,::2]=np.array([100,100,100,100])
new_arr

array([[100,   7, 100,   2, 100,   2, 100,   6],
       [100,   3, 100,   5, 100,   8, 100,   3],
       [100,   2, 100,   3, 100,   5, 100,   3],
       [100,   4, 100,   3, 100,   4, 100,   1]])

In [119]:
# 切片修改值
arr1=np.random.randint(1,9,12)
arr1

array([2, 8, 6, 4, 8, 8, 1, 8, 6, 3, 5, 8])

In [120]:
# 用列表赋值
arr1[::2]=np.array([0,0,0,0,0,0])
# 查看原数组
arr1

array([0, 8, 0, 4, 0, 8, 0, 8, 0, 3, 0, 8])

In [121]:
# 举个例子
a=np.array([(0,1,2,3,4,5),
           (10,11,12,13,14,15),
           (20,21,22,23,24,25),
           (30,31,32,33,34,35),
           (40,41,42,43,44,45),
           (50,51,52,53,54,55)])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [122]:
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [123]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [124]:
mask=np.array([1,0,1,0,0,1],dtype=np.bool)
a[mask,2]

array([ 2, 22, 52])

# 花式索引

In [125]:
# 花式索引，修改新数组不会影响原数组
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [126]:
print(u'获取第0，3，5行的数据')
print(arr[[0,3,5]])

获取第0，3，5行的数据
[[ 0  1  2  3]
 [12 13 14 15]
 [20 21 22 23]]


In [127]:
print(u'获取第(0,0)，(3,3)，(5,2)这三个索引位置的数据')
print(arr[[0,3,5],[0,3,2]])

获取第(0,0)，(3,3)，(5,2)这三个索引位置的数据
[ 0 15 22]


In [128]:
print(u'使用转置的方式获取第0，3，5行的第0，2，3列的数据')
print(arr[[0,3,5]].T[[0,2,3]].T)

使用转置的方式获取第0，3，5行的第0，2，3列的数据
[[ 0  2  3]
 [12 14 15]
 [20 22 23]]


In [129]:
print(u'使用索引器获取第（0，3，5）行的第（0，2，3）列的数据')
arr[np.ix_([0,3,5],[0,2,3])]# 通过ix_索引器，可以分别获取每一行对应位置的下标元素

使用索引器获取第（0，3，5）行的第（0，2，3）列的数据


array([[ 0,  2,  3],
       [12, 14, 15],
       [20, 22, 23]])

# 布尔类型索引

In [130]:
A=np.random.random((4,4))
print(A.shape)
A

(4, 4)


array([[0.6996004 , 0.46195943, 0.3678555 , 0.84550931],
       [0.34853799, 0.79297943, 0.85813603, 0.93438715],
       [0.96566139, 0.87832526, 0.94151013, 0.74820822],
       [0.02191662, 0.74068926, 0.28896819, 0.51700841]])

In [131]:
B=A<0.5
print(B.shape)
B

(4, 4)


array([[False,  True,  True, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

In [132]:
# True位置的元素取出来形成一个新的数组，要求A的shape和B的shape是一致的
C=A[B]
print(C.shape)
C

(5,)


array([0.46195943, 0.3678555 , 0.34853799, 0.02191662, 0.28896819])

In [133]:
# Numpy中不能用and，or，not。用&（逻辑与）、|（逻辑或）、~（逻辑非）来代替
names=np.array(['Gerry','Tom','John'])
scores=np.array([
    [76,85,64,56],
    [86,65,97,67],
    [56,87,77,78]
])
classes=np.array([u'语文',u'数学',u'英语',u'科学'])
print('Gerry score is:',scores[names=='Gerry'].reshape((-1)))
print('Gerry 数学 score is:',scores[names=='Gerry'].reshape((-1,))[classes==u'数学'])
print(u'Gerry和Tom的成绩')
print(scores[(names=='Gerry')|(names=='Tom')])
print('非Gerry和Tom的成绩')
print(scores[(names!='Gerry')&(names!='Tom')])

Gerry score is: [76 85 64 56]
Gerry 数学 score is: [85]
Gerry和Tom的成绩
[[76 85 64 56]
 [86 65 97 67]]
非Gerry和Tom的成绩
[[56 87 77 78]]


# 数组转置与轴对换

In [134]:
arr=np.arange(40).reshape(5,-1)
print(u'原数组的shape：',arr.shape)
arr

原数组的shape： (5, 8)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [135]:
arr1=arr.transpose()
print('通过函数transpose转置后数组的shape值：',arr1.shape)
arr1

通过函数transpose转置后数组的shape值： (8, 5)


array([[ 0,  8, 16, 24, 32],
       [ 1,  9, 17, 25, 33],
       [ 2, 10, 18, 26, 34],
       [ 3, 11, 19, 27, 35],
       [ 4, 12, 20, 28, 36],
       [ 5, 13, 21, 29, 37],
       [ 6, 14, 22, 30, 38],
       [ 7, 15, 23, 31, 39]])

In [136]:
arr2=arr.T
print('通过属性T转置后数组的shape值：',arr2.shape)
arr2

通过属性T转置后数组的shape值： (8, 5)


array([[ 0,  8, 16, 24, 32],
       [ 1,  9, 17, 25, 33],
       [ 2, 10, 18, 26, 34],
       [ 3, 11, 19, 27, 35],
       [ 4, 12, 20, 28, 36],
       [ 5, 13, 21, 29, 37],
       [ 6, 14, 22, 30, 38],
       [ 7, 15, 23, 31, 39]])

In [137]:
arr=np.random.randint(0,10,(4,3,2))
arr

array([[[2, 1],
        [2, 2],
        [7, 6]],

       [[5, 8],
        [3, 5],
        [9, 2]],

       [[4, 4],
        [4, 2],
        [0, 9]],

       [[6, 3],
        [8, 6],
        [2, 5]]])

In [138]:
arr.transpose(1,2,0)

array([[[2, 5, 4, 6],
        [1, 8, 4, 3]],

       [[2, 3, 4, 8],
        [2, 5, 2, 6]],

       [[7, 9, 0, 2],
        [6, 2, 9, 5]]])

# 数组拉伸与合并

In [14]:
arr=np.array([[3,9],[4,6]])
arr

array([[3, 9],
       [4, 6]])

In [140]:
# 横向拉伸2倍
np.tile(arr,2)

array([[3, 9, 3, 9],
       [4, 6, 4, 6]])

In [15]:
# 纵向拉伸3倍，横向拉伸1倍
np.tile(arr,(3,1))

array([[3, 9],
       [4, 6],
       [3, 9],
       [4, 6],
       [3, 9],
       [4, 6]])

In [16]:
# 纵向拉伸3倍，横向拉伸2倍
np.tile(arr,(3,2))

array([[3, 9, 3, 9],
       [4, 6, 4, 6],
       [3, 9, 3, 9],
       [4, 6, 4, 6],
       [3, 9, 3, 9],
       [4, 6, 4, 6]])

In [24]:
arr1=np.random.randint(1,9,(3,2,4))
print(arr1.shape)  # 可以理解为3个 (2,4)的数组进行堆叠
arr1

(3, 2, 4)


array([[[4, 2, 3, 7],
        [2, 4, 8, 1]],

       [[6, 1, 5, 5],
        [7, 3, 8, 2]],

       [[4, 7, 6, 2],
        [5, 4, 8, 5]]])

In [25]:
arr2=np.stack(arr1,axis=0)
print(arr2.shape)
arr2

(3, 2, 4)


array([[[4, 2, 3, 7],
        [2, 4, 8, 1]],

       [[6, 1, 5, 5],
        [7, 3, 8, 2]],

       [[4, 7, 6, 2],
        [5, 4, 8, 5]]])

In [26]:
arr3=np.stack(arr1,axis=1)
print(arr3.shape)   # axis=1的位置插入维度，由于一共3个数组，所以堆叠后的形状为2*3*4
arr3

(2, 3, 4)


array([[[4, 2, 3, 7],
        [6, 1, 5, 5],
        [4, 7, 6, 2]],

       [[2, 4, 8, 1],
        [7, 3, 8, 2],
        [5, 4, 8, 5]]])

In [27]:
arr4=np.stack(arr1,axis=2)
print(arr4.shape)
arr4

(2, 4, 3)


array([[[4, 6, 4],
        [2, 1, 7],
        [3, 5, 6],
        [7, 5, 2]],

       [[2, 7, 5],
        [4, 3, 4],
        [8, 8, 8],
        [1, 2, 5]]])

In [34]:
a=np.array([1,2,3])
b=np.array([2,3,4])

In [36]:
a1=np.stack((a,b),axis=0)
print(a1.shape)
a1

(2, 3)


array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
a2=np.stack((a,b),axis=1)
print(a2.shape)
a2

(3, 2)


array([[1, 2],
       [2, 3],
       [3, 4]])

In [38]:
# hstack()函数，横向合并
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [39]:
# vstack()函数，纵向合并
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
a=np.array([
    [1,2,3,44],
    [22,32,42,42],
    [23,3,3,43]
])
b=np.array([
    [1,3,2,44],
    [42,52,62,42],
    [23,3,3,43]
])

In [41]:
np.stack((a,b),axis=0)    #第一个维度增加

(2, 3, 4)


array([[[ 1,  2,  3, 44],
        [22, 32, 42, 42],
        [23,  3,  3, 43]],

       [[ 1,  3,  2, 44],
        [42, 52, 62, 42],
        [23,  3,  3, 43]]])

In [42]:
np.stack((a,b),axis=1)

(3, 2, 4)


array([[[ 1,  2,  3, 44],
        [ 1,  3,  2, 44]],

       [[22, 32, 42, 42],
        [42, 52, 62, 42]],

       [[23,  3,  3, 43],
        [23,  3,  3, 43]]])

In [33]:
np.stack((a,b),axis=-1)    #最后一个维度增加

array([[[ 1,  1],
        [ 2,  3],
        [ 3,  2],
        [44, 44]],

       [[22, 42],
        [32, 52],
        [42, 62],
        [42, 42]],

       [[23, 23],
        [ 3,  3],
        [ 3,  3],
        [43, 43]]])

In [142]:
a=[[1,2,3],
   [4,5,6]]
b=[[1,2,3],
   [4,5,6]]
c=[[1,2,3],
   [4,5,6]]
d=[[1,2,3],
   [4,5,6]]
e=[1,2,3]
f=[4,5,6]

In [143]:
# axis表示往某个维度添加一维
np.stack((e,)) # 默认axis=0

array([[1, 2, 3]])

In [144]:
np.stack((e,f))

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
# 在一维数组f上的第一维度添加
np.stack((f,),axis=1)

array([[4],
       [5],
       [6]])

In [146]:
# 在两个二维数组的第一维度添加并且合并
np.stack((a,b),axis=1)

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [147]:
# 在三个二维数组的第二维度添加并且合并
np.stack((a,b,c),axis=2)

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]])

In [148]:
# hstack()函数，横向合并
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [149]:
# vstack()函数，纵向合并
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# 通用函数/常用函数(一元函数)

In [150]:
arr=np.array([-5.3,-6.2,-5,0,4.2,5,3,2,1])
print('arr=',arr)
print('绝对值函数abs',np.abs(arr))
print('复数绝对值函数fabs',np.fabs(arr))
print('sqrt 开根号',np.sqrt(np.fabs(arr)))
print('square 开根号',np.square(arr))
print('exp 自然对数e的x次方',np.exp(arr))

arr= [-5.3 -6.2 -5.   0.   4.2  5.   3.   2.   1. ]
绝对值函数abs [5.3 6.2 5.  0.  4.2 5.  3.  2.  1. ]
复数绝对值函数fabs [5.3 6.2 5.  0.  4.2 5.  3.  2.  1. ]
sqrt 开根号 [2.30217289 2.48997992 2.23606798 0.         2.04939015 2.23606798
 1.73205081 1.41421356 1.        ]
square 开根号 [28.09 38.44 25.    0.   17.64 25.    9.    4.    1.  ]
exp 自然对数e的x次方 [4.99159391e-03 2.02943064e-03 6.73794700e-03 1.00000000e+00
 6.66863310e+01 1.48413159e+02 2.00855369e+01 7.38905610e+00
 2.71828183e+00]


In [151]:
log_arr=np.fabs(arr)+1
print('log 对数函数，默认以e为底',np.log(log_arr))
print('log 对数函数，以10为底',np.log10(log_arr))
print('log 对数函数，以2为底',np.log2(log_arr))
print('log 对数函数，以(x+1)为底求x的值',np.log1p(log_arr))
print('sign 判断矩阵中各元素的正负号',np.sign(arr))
print('ceil 向上取整',np.ceil(arr))
print('floor 向下取整',np.floor(arr))
print('rint 四舍五入',np.rint(arr))

log 对数函数，默认以e为底 [1.84054963 1.97408103 1.79175947 0.         1.64865863 1.79175947
 1.38629436 1.09861229 0.69314718]
log 对数函数，以10为底 [0.79934055 0.8573325  0.77815125 0.         0.71600334 0.77815125
 0.60205999 0.47712125 0.30103   ]
log 对数函数，以2为底 [2.65535183 2.84799691 2.5849625  0.         2.37851162 2.5849625
 2.         1.5849625  1.        ]
log 对数函数，以(x+1)为底求x的值 [1.98787435 2.10413415 1.94591015 0.69314718 1.82454929 1.94591015
 1.60943791 1.38629436 1.09861229]
sign 判断矩阵中各元素的正负号 [-1. -1. -1.  0.  1.  1.  1.  1.  1.]
ceil 向上取整 [-5. -6. -5.  0.  5.  5.  3.  2.  1.]
floor 向下取整 [-6. -7. -5.  0.  4.  5.  3.  2.  1.]
rint 四舍五入 [-5. -6. -5.  0.  4.  5.  3.  2.  1.]


In [152]:
print('modf 分别返回整数部分和小数部分',np.modf(arr))
print('isnan 判断元素是不是缺省值NaN数据类型',np.isnan(arr))
print('isfinite 判断元素是不是有穷的',np.isfinite(arr))
print('isinf 判断元素是不是无穷的',np.isinf(arr))
print('cos 三角函数',np.cos(arr))
print('cosh 双曲型三角函数',np.cosh(arr))
print('arccos 反三角函数',np.arccos(np.cos(arr)))
print('arccosh 双曲型反三角函数',np.arccosh(np.cosh(arr)))

modf 分别返回整数部分和小数部分 (array([-0.3, -0.2, -0. ,  0. ,  0.2,  0. ,  0. ,  0. ,  0. ]), array([-5., -6., -5.,  0.,  4.,  5.,  3.,  2.,  1.]))
isnan 判断元素是不是缺省值NaN数据类型 [False False False False False False False False False]
isfinite 判断元素是不是有穷的 [ True  True  True  True  True  True  True  True  True]
isinf 判断元素是不是无穷的 [False False False False False False False False False]
cos 三角函数 [ 0.55437434  0.9965421   0.28366219  1.         -0.49026082  0.28366219
 -0.9899925  -0.41614684  0.54030231]
cosh 双曲型三角函数 [100.17090078 246.37553526  74.20994852   1.          33.35066331
  74.20994852  10.067662     3.76219569   1.54308063]
arccos 反三角函数 [0.98318531 0.08318531 1.28318531 0.         2.08318531 1.28318531
 3.         2.         1.        ]
arccosh 双曲型反三角函数 [5.3 6.2 5.  0.  4.2 5.  3.  2.  1. ]


# 通用函数/常用函数(二元函数)

In [5]:
arr1=np.array([1,2,8,1])
arr2=np.array([4,5,6,0])
print('mod 求模(取余)运算',np.mod(arr2,arr1))
print('dot 向量内积运算(点乘)',np.dot(arr1,arr2))
print('greater 大于',np.greater(arr1,arr2))
print('greater_equal 大于等于',np.greater_equal(arr1,arr2))
print('less 小于',np.less(arr1,arr2))
print('equal 等于',np.equal(arr1,arr2))
print('not_equal 不等于',np.not_equal(arr1,arr2))
print('logical_and 逻辑与',np.logical_and(arr1,arr2))  
print('logical_or 逻辑或',np.logical_or(arr1,arr2))    
print('logical_xor 逻辑异或',np.logical_xor(arr1,arr2))  # 两者不同返回真，相同返回假
print('power 指数运算',np.power(arr1,3))

mod 求模(取余)运算 [0 1 6 0]
dot 向量内积运算(点乘) 62
greater 大于 [False False  True  True]
greater_equal 大于等于 [False False  True  True]
less 小于 [ True  True False False]
equal 等于 [False False False False]
not_equal 不等于 [ True  True  True  True]
logical_and 逻辑与 [ True  True  True False]
logical_or 逻辑或 [ True  True  True  True]
logical_xor 逻辑异或 [False False False  True]
power 指数运算 [  1   8 512   1]


In [6]:
arr1=np.random.randint(1,9,(3,3))
arr2=np.random.randint(1,9,(3,3))
print('mod 求模(取余)运算',np.mod(arr2,arr1))
print('dot 向量内积运算(点乘)',np.dot(arr1,arr2))
print('greater 大于',np.greater(arr1,arr2))
print('greater_equal 大于等于',np.greater_equal(arr1,arr2))
print('less 小于',np.less(arr1,arr2))
print('equal 等于',np.equal(arr1,arr2))
print('not_equal 不等于',np.not_equal(arr1,arr2))
print('logical_and 逻辑与',np.logical_and(arr1,arr2))  
print('logical_or 逻辑或',np.logical_or(arr1,arr2))    
print('logical_xor 逻辑异或',np.logical_xor(arr1,arr2)) 

mod 求模(取余)运算 [[4 1 1]
 [3 0 2]
 [4 1 1]]
dot 向量内积运算(点乘) [[64 49 45]
 [50 43 27]
 [56 39 43]]
greater 大于 [[ True  True  True]
 [ True False False]
 [ True False  True]]
greater_equal 大于等于 [[ True  True  True]
 [ True False False]
 [ True False  True]]
less 小于 [[False False False]
 [False  True  True]
 [False  True False]]
equal 等于 [[False False False]
 [False False False]
 [False False False]]
not_equal 不等于 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
logical_and 逻辑与 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
logical_or 逻辑或 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
logical_xor 逻辑异或 [[False False False]
 [False False False]
 [False False False]]


In [7]:
arr1=np.array([1,0,1,0,1])
arr2=np.array([0,1,1,0,0])
print('mod 求模(取余)运算',np.mod(arr2,arr1))
print('dot 向量内积运算(点乘)',np.dot(arr1,arr2))
print('greater 大于',np.greater(arr1,arr2))
print('greater_equal 大于等于',np.greater_equal(arr1,arr2))
print('less 小于',np.less(arr1,arr2))
print('equal 等于',np.equal(arr1,arr2))
print('not_equal 不等于',np.not_equal(arr1,arr2))
print('logical_and 逻辑与',np.logical_and(arr1,arr2))  
print('logical_or 逻辑或',np.logical_or(arr1,arr2))    
print('logical_xor 逻辑异或',np.logical_xor(arr1,arr2))

mod 求模(取余)运算 [0 0 0 0 0]
dot 向量内积运算(点乘) 1
greater 大于 [ True False False False  True]
greater_equal 大于等于 [ True False  True  True  True]
less 小于 [False  True False False False]
equal 等于 [False False  True  True False]
not_equal 不等于 [ True  True False False  True]
logical_and 逻辑与 [False False  True False False]
logical_or 逻辑或 [ True  True  True False  True]
logical_xor 逻辑异或 [ True  True False False  True]


G:\py\anaconda64\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in remainder
  This is separate from the ipykernel package so we can avoid doing imports until


# 聚合函数

In [154]:
arr=np.random.randint(1,9,(2,3))
arr

array([[1, 6, 5],
       [5, 1, 5]])

In [155]:
print('min',np.amin(arr))
print('max',np.amax(arr))
print('mean',np.mean(arr))
print('mean',arr.mean())

min 1
max 6
mean 3.8333333333333335
mean 3.8333333333333335


In [156]:
# 方差——偏差的平方的平均值
a=np.array([[5,2,3,4],[7,3,9,1]])
print(np.mean((a-a.mean())**2))

6.1875


In [157]:
# 标准差——偏差的平方的平均值的平方根
print(np.sqrt(np.mean((a-a.mean())**2)))
print(np.std(a))

2.48746859276655
2.48746859276655


In [158]:
arr=np.array([[1,2,3,4],[7,8,9,10]])
print('arr=',arr)
print('min=',arr.min())
print('max=',arr.max())
print('mean=',arr.mean())
print('std=',arr.std())
print(u'根据方差公式计算的方差值为：',np.sqrt(np.power(arr-arr.mean(),2).sum()/arr.size))

arr= [[ 1  2  3  4]
 [ 7  8  9 10]]
min= 1
max= 10
mean= 5.5
std= 3.2015621187164243
根据方差公式计算的方差值为： 3.2015621187164243


In [46]:
# 二维数组的情况下，axis=0表示对同列的数据进行聚合；axis=1表示对同行的数据进行聚合
arr=np.array([
    [
        1,3,5,9
    ],
    [
        2,4,6,8
    ],
    [
        -5,-6,-8,-2
    ]
])
print('=====arr=====')
print(arr)
print('对同列上的元素求平均值：',arr.mean(axis=0))
print('对同行上的元素求平均值：',arr.mean(axis=1))
print('对同行上的元素求和：',arr.sum(axis=1))
print('对同行上的元素求最大值：',arr.max(axis=1))
print('对同行上的元素求标准差：',arr.std(axis=1))
print('所有元素的标准差：',np.sqrt(np.mean((arr-arr.mean())**2)))

=====arr=====
[[ 1  3  5  9]
 [ 2  4  6  8]
 [-5 -6 -8 -2]]
对同列上的元素求平均值： [-0.66666667  0.33333333  1.          5.        ]
对同行上的元素求平均值： [ 4.5   5.   -5.25]
对同行上的元素求和： [ 18  20 -21]
对同行上的元素求最大值： [ 9  8 -2]
对同行上的元素求标准差： [2.95803989 2.23606798 2.16506351]
所有元素的标准差： 5.330077130982461


# np.where函数

In [160]:
?np.where

In [48]:
# 取出arr1 arr2中对应位数上的较小值：
arr1 = np.array([1,3,5,7])
arr2 = np.array([3,5,2,1])
condition = arr1 < arr2
arr3 = [x if c else y for c,x,y in zip(condition,arr1,arr2) ]    
# zip打包3个列表      #然后通过for遍历列表
print(arr3)
np.where(condition,arr1,arr2)

[1, 3, 2, 1]


array([1, 3, 2, 1])

In [3]:
# 二维
arr4=np.where([[True,False],[True,True]],[[1,2],[3,4]],[[9,8],[7,6]])
arr4

array([[1, 8],
       [3, 4]])

In [161]:
xarr=np.array([-1.1,-1.2,-1.3,-1.4,-1.5])
yarr=np.array([-2.1,-2.2,-2.3,-2.4,-2.5])
condition=xarr<yarr
result1=[x if c else y for (x,y,c) in zip(xarr,yarr,condition)]
result2=np.where(condition,xarr,yarr)
print(u'使用python的语法，结果为：',result1,'；数据类型为：',type(result1))
print(u'使用np.where的语法，结果为：',result2,'；数据类型为：',type(result2))

使用python的语法，结果为： [-2.1, -2.2, -2.3, -2.4, -2.5] ；数据类型为： <class 'list'>
使用np.where的语法，结果为： [-2.1 -2.2 -2.3 -2.4 -2.5] ；数据类型为： <class 'numpy.ndarray'>


In [162]:
# 练习：将数组中的所有异常数字替换为0，比如将NaN替换为0
arr=np.array([
    [1,2,np.NaN,4],
    [4,5,6,np.NaN],
    [7,8,9,np.inf],
    [np.inf,np.e,np.pi,4]
])
condition=np.isnan(arr)|np.isinf(arr)#得到判断条件
print('原始数组')
print(arr)
print()
print('结果')
print(np.where(condition,0,arr))

原始数组
[[1.         2.                nan 4.        ]
 [4.         5.         6.                nan]
 [7.         8.         9.                inf]
 [       inf 2.71828183 3.14159265 4.        ]]

结果
[[1.         2.         0.         4.        ]
 [4.         5.         6.         0.        ]
 [7.         8.         9.         0.        ]
 [0.         2.71828183 3.14159265 4.        ]]


# np.unique函数

In [163]:
arr=np.array([u'图书',u'数码',u'小吃',u'数码',u'女装',u'小吃',u'美食',u'男装',u'数码'])
print('=====原始数据=====')
for a in arr:
    print(a,end='，')
print()

arr2=np.unique(arr)
print('=====去重后数据=====')
for a in arr2:
    print(a,end='，')
print()

=====原始数据=====
图书，数码，小吃，数码，女装，小吃，美食，男装，数码，
=====去重后数据=====
图书，女装，小吃，数码，男装，美食，
