In [2]:
import numpy as np
B = np.arange(3)
print (B)
print (np.exp(B))
print (np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [11]:
#Return the floor of the input
b=np.random.random((3,4))
print(b)
a = np.floor(10*b)
print (a)
print ('--------')
print(a.shape)
## flatten the array
print (a.ravel())
print ('--------')
a.shape = (6, 2)
print (a) 
print ('--------')
print (a.T)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
print(a.reshape(3,-1))

[[0.99172624 0.61018467 0.16474646 0.11934687]
 [0.33936912 0.50774099 0.09295327 0.61628149]
 [0.74284054 0.71179083 0.0597464  0.97981425]]
[[9. 6. 1. 1.]
 [3. 5. 0. 6.]
 [7. 7. 0. 9.]]
--------
(3, 4)
[9. 6. 1. 1. 3. 5. 0. 6. 7. 7. 0. 9.]
--------
[[9. 6.]
 [1. 1.]
 [3. 5.]
 [0. 6.]
 [7. 7.]
 [0. 9.]]
--------
[[9. 1. 3. 0. 7. 0.]
 [6. 1. 5. 6. 7. 9.]]
[[9. 6. 1. 1.]
 [3. 5. 0. 6.]
 [7. 7. 0. 9.]]


In [12]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print (a)
print ('---')
print (b)
print ('---')
print (np.vstack((a,b)))
print(np.hstack((a,b)))

[[8. 2.]
 [6. 8.]]
---
[[2. 7.]
 [2. 2.]]
---
[[8. 2.]
 [6. 8.]
 [2. 7.]
 [2. 2.]]
[[8. 2. 2. 7.]
 [6. 8. 2. 2.]]


In [17]:
a = np.floor(10*np.random.random((2,12)))
print (a)
print ('---')
print (np.hsplit(a,3))
print ('---')
print (np.hsplit(a,(3,4)))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print ('---')
print (a)
np.vsplit(a,3)

[[3. 3. 1. 1. 0. 9. 7. 7. 8. 6. 4. 4.]
 [6. 8. 9. 1. 1. 4. 2. 4. 6. 2. 7. 8.]]
---
[array([[3., 3., 1., 1.],
       [6., 8., 9., 1.]]), array([[0., 9., 7., 7.],
       [1., 4., 2., 4.]]), array([[8., 6., 4., 4.],
       [6., 2., 7., 8.]])]
---
[array([[3., 3., 1.],
       [6., 8., 9.]]), array([[1.],
       [1.]]), array([[0., 9., 7., 7., 8., 6., 4., 4.],
       [1., 4., 2., 4., 6., 2., 7., 8.]])]
---
[[3. 7.]
 [4. 6.]
 [4. 0.]
 [0. 5.]
 [4. 8.]
 [8. 0.]
 [8. 1.]
 [9. 6.]
 [7. 5.]
 [4. 9.]
 [6. 8.]
 [7. 0.]]


[array([[3., 7.],
        [4., 6.],
        [4., 0.],
        [0., 5.]]), array([[4., 8.],
        [8., 0.],
        [8., 1.],
        [9., 6.]]), array([[7., 5.],
        [4., 9.],
        [6., 8.],
        [7., 0.]])]

In [18]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print (b is a)
b.shape = 3,4
print (a.shape)
print (id(a))
print (id(b))

True
(3, 4)
1934150565520
1934150565520


In [22]:
#The view method creates a new array object that looks at the same data.
c = a.view()
print (c is a)
c.shape = 2,6
print (a.shape)
c[0,4] = 1234
print(c)
print (a)
print (id(a))
print (id(c))

False
(3, 4)
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
1934150565520
1934150615888


In [23]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
print(d is a)
d[0,0] = 9999
print (d) 
print (a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
