In [4]:
import numpy as np
#1:8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#2：min()、max()函数

In [10]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()

In [8]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((5,5))
print(z)
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print(z)

[[7.48171013 4.98457766 7.34357301 7.87645817 5.58681159]
 [5.23755222 9.02075928 7.13986114 5.89478094 6.65701493]
 [1.81965399 8.34678575 3.92927398 6.66590571 1.6714492 ]
 [9.6878074  9.9365779  2.89670077 7.4886111  0.90022714]
 [0.02820255 2.83819794 9.3769243  2.67966285 1.28120754]]
[[0.75224316 0.50022077 0.73830171 0.792083   0.56100106]
 [0.52575215 0.90757126 0.71774215 0.59208278 0.66901103]
 [0.18080173 0.83955067 0.39371454 0.66990833 0.16584421]
 [0.97489291 1.         0.28950238 0.75293964 0.08800884]
 [0.         0.283598   0.94351712 0.26759789 0.12645918]]


In [11]:
#矩阵相加
z = np.zeros((5,5))
z += np.arange(5)
print (np.arange(5))
print (z)


[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [12]:
#生成0~10之间均匀分布的11个数，包括0和10

z = np.linspace(0,10,11,endpoint=True,retstep=True)
print (z)


(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [18]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [2]:
import numpy as np
a = np.array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55],
       [ 1,  2,  3,  4,  5,  6]])


In [12]:
a[2:5:2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [9]:
b=[3,5]
a[b,::2]

array([[30, 32, 34],
       [50, 52, 54]])