In [1]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction import DictVectorizer,FeatureHasher
import numpy as np
import pandas as pd
from pandas import DataFrame

In [14]:
# OneHotEncoder要求数据类别必须是数值的
# categorical_features：给定对那些列的数据进行哑编码操作，默认是对所有类数据做
# n_values：明确给定各个特征属性的类别数目，其实是最大值-最小值+1
# enc = OneHotEncoder(categorical_features=[1,2])
# enc = OneHotEncoder(n_values=[3, 3, 4])
enc = OneHotEncoder()
a=np.array([[0, 0, 3], [2, 1, 0], [0, 2, 1], [1, 0, 2],[1,1,1]])
enc.fit(a) 
print(a)
print("编码结果",enc.n_values_)
print("原来的特征(进行哑编码的)在新的特征矩阵中的位置映射关系:")
print(enc.feature_indices_)
enc.transform([[1, 2, 2],[2, 2, 2]]).toarray()

[[0 0 3]
 [2 1 0]
 [0 2 1]
 [1 0 2]
 [1 1 1]]
编码结果 [3 3 4]
原来的特征(进行哑编码的)在新的特征矩阵中的位置映射关系:
[ 0  3  6 10]


array([[ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.]])

In [3]:
# 如果类别数据是字符串类型的，可以使用pandas的API进行哑编码转换
a = DataFrame([
    ['a', 1, 2],
    ['b', 1, 1],
    ['a', 2, 1],
    ['c', 1, 2],
    ['c', 1, 2]
], columns=['c1', 'c2', 'c3'])
a = pd.get_dummies(a)
a

c2  c3  c1_a  c1_b  c1_c
0   1   2     1     0     0
1   1   1     0     1     0
2   2   1     1     0     0
3   1   2     0     0     1
4   1   2     0     0     1

In [4]:
# sparse：最终产生的结果是否是稀疏化矩阵，默认为True，一般不改动
dv = DictVectorizer(sparse=False)
D = [{'foo':1, 'bar':2.2}, {'foo':3, 'baz': 2}]
X = dv.fit_transform(D)
print (X)
# 直接把字典中的key作为特征，value作为特征值，然后构建特征矩阵
print (dv.get_feature_names())
print (dv.transform({'foo':4, 'unseen':3}))

[[ 2.2  0.   1. ]
 [ 0.   2.   3. ]]
['bar', 'baz', 'foo']
[[ 0.  0.  4.]]


In [5]:
h = FeatureHasher(n_features=3)
D = [{'dog': 1, 'cat':2, 'elephant':4},{'dog': 2, 'run': 5}]
# 直接以hash值计算结果 -- 该方式一般不用
f = h.transform(D)
f.toarray()

array([[-1.,  2., -4.],
       [-2., -5.,  0.]])