In [11]:
import numpy as np
from sklearn.preprocessing import Binarizer

In [12]:
arr = np.array([
    [1.5, 2.3, 1.9],
    [0.5, 0.5, 1.6],
    [1.1, 2, 0.2]
])

In [13]:
# 针对所有的特征属性选择同一个阈值
binarizer = Binarizer(threshold=2.0)
binarizer.fit(arr)
binarizer

Binarizer(copy=True, threshold=2.0)

In [14]:
binarizer.transform(arr)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
# 使用不同的阈值来选择不同的特征属性
binarizer = Binarizer(threshold=[1.0,2.0,1.0])
binarizer.fit(arr)
binarizer.transform(arr)

array([[ 1.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [15]:
# 使用不同的阈值来选择不同的特征属性
f1 = Binarizer(threshold=1.0).transform(arr[:,0].reshape((-1,1)))
f2 = Binarizer(threshold=2.0).transform(arr[:,1].reshape((-1,1)))
f3 = Binarizer(threshold=1.6).transform(arr[:,2].reshape((-1,1)))
f = np.concatenate((f1, f2, f3), axis=1)
f

array([[ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.]])

## 备注：

1. 一般情况下，对于每个特征需要使用不同的阈值进行二值化操作
2. 一般情况下，对数据进行划分的时候，不是进行二值化，而是进行多值化(分区化/分桶化)；即：将一个连续的数据，按照不同的取值范围，分为不同的级别；比如：在某一个模型中，存在人的收入情况，单位为元，根据业务来判断的话，可能会得到影响因变量的因素其实是区间后的收入情况，那么这个时候就可以基于业务的特征，将收入划分为收入等级，比如：1w -> 0, 1w~2w -> 1, 2w~3w -> 2, 3w+ -> 3(至于这里到底做不做哑编码操作，具体的看对于区间化之后的数据的理解。如果认为区间化之后的特征数据是具有等级意义的，那么就可以考虑不做哑编码。如果认为区间化之后的数据是一个类别数据，那么一般需要做哑编码操作)
